Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np

Aa=np.array([[1.,2.],[3.,4.]])
Ba=np.array([[5.,6.],[7.,8.]])

print("el tipo de datos de Aa es:", type(Aa), "\n")
# realizamos la operaci√≥n multiplicaci√≥n elemento a elemento
print("resultado multiplicaci√≥n elemento a elemento:\n", A*B, "\n\n")

Am=np.matrix([[1.,2.],[3.,4.]])
Bm=np.matrix([[5.,6.],[7.,8.]])

print("el tipo de datos de Ama es:", type(Am), "\n")
# relizamos la operaci√≥n multiplicaci√≥n elemento a elemento
print("resultado multiplicaci√≥n de matrices usando matrix:\n", Am*Bm, "\n\n")
print("resultado multiplicaci√≥n de matrices usando ndarray:\n", Am@Bm)
------------------

----- stdout -----
el tipo de datos de Aa es: <class 'numpy.ndarray'>
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[42], line 8[0m
[1;32m      6[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mel tipo de datos de Aa es:[39m[38;5;124m"[39m, [38;5;28mtype[39m(Aa), [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m)
[1;32m      7[0m [38;5;66;03m# realizamos la operaci√≥n multiplicaci√≥n elemento a elemento[39;00m
[0;32m----> 8[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mresultado multiplicaci√≥n elemento a elemento:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m, [43mA[49m[38;5;241m*[39mB, [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m)
[1;32m     10[0m Am[38;5;241m=[39mnp[38;5;241m.[39mmatrix([[[38;5;241m1.[39m,[38;5;241m2.[39m],[[38;5;241m3.[39m,[38;5;241m4.[39m]])
[1;32m     11[0m Bm[38;5;241m=[39mnp[38;5;241m.[39mmatrix([[[38;5;241m5.[39m,[38;5;241m6.[39m],[[38;5;241m7.[39m,[38;5;241m8.[39m]])

[0;31mNameError[0m: name 'A' is not defined

